[package]
name = "native"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
flowcontrol = "0.2.2"
good-ormning-runtime = { version = "0.1", features = ["sqlite"] }
rusqlite = "0.32"
sea-query = { version = "0.32", default-features = false, features = [
    "backend-sqlite",
], path = "/home/andrew/temp/soft/fork-sea-query" }
sea-query-rusqlite = { version = "0.7", features = [
    "with-json",
], path = "/home/andrew/temp/soft/fork-sea-query/sea-query-rusqlite" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[build-dependencies]
good-ormning = { version = "0.1", features = ["sqlite", "chrono"] }
