[unstable]
build-std = ['std', 'panic_abort']

[build]
rustflags = [
    "-Ctarget-feature=+atomics,+bulk-memory,+mutable-globals",
    "--cfg=web_sys_unstable_apis",
]
target = "wasm32-unknown-unknown"
