import fs from "node:fs";
import * as default_config from "./default_config.ts";

// Form/view IDs used by the browser extension.
// If a name here doesn't match the config, this script will fail at the
// buildGlobal() call or at the assertion below.
const EXTENSION_FORM_IDS = [
  "capture-microblog",
  "capture-profile",
  "capture-image",
] as const;

const EXTENSION_VIEW_IDS = [
  "microblog-exists",
  "profile-exists",
  "image-exists",
] as const;

function toPascalCase(s: string): string {
  return s
    .split(/[-_]/)
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join("");
}

(async () => {
  const config = await default_config.buildGlobal();

  // Validate and extract form parameter names
  const forms: Record<string, string[]> = {};
  for (const formId of EXTENSION_FORM_IDS) {
    const form = config.forms[formId];
    if (!form) {
      throw new Error(
        `Browser extension form "${formId}" not found in config`,
      );
    }
    // Collect field IDs that aren't auto-generated (id, datetime_now)
    forms[formId] = form.fields
      .filter((f) => f.type !== "id" && f.type !== "datetime_now")
      .map((f) => f.id);
  }

  // Validate and extract view parameter names
  const views: Record<string, string[]> = {};
  for (const viewId of EXTENSION_VIEW_IDS) {
    const view = config.views[viewId];
    if (!view) {
      throw new Error(
        `Browser extension view "${viewId}" not found in config`,
      );
    }
    views[viewId] = Object.keys(view.parameters ?? {});
  }

  // Generate typedefs for each form's parameter union
  const typedefs: string[] = [];
  for (const [id, params] of Object.entries(forms)) {
    const name = toPascalCase(id) + "Param";
    const union = params.map((p) => `"${p}"`).join(" | ");
    typedefs.push(`/** @typedef {${union}} ${name} */`);
  }
  for (const [id, params] of Object.entries(views)) {
    const name = toPascalCase(id) + "Param";
    const union = params.map((p) => `"${p}"`).join(" | ");
    typedefs.push(`/** @typedef {${union}} ${name} */`);
  }

  // Generate form entries
  const formEntries = Object.entries(forms)
    .map(([id, params]) => {
      const typeName = toPascalCase(id) + "Param";
      return `  "${id}": {
    id: /** @type {"${id}"} */ ("${id}"),
    params: /** @type {${typeName}[]} */ ([${params.map((p) => `"${p}"`).join(", ")}]),
  }`;
    })
    .join(",\n");

  // Generate view entries
  const viewEntries = Object.entries(views)
    .map(([id, params]) => {
      const typeName = toPascalCase(id) + "Param";
      return `  "${id}": {
    id: /** @type {"${id}"} */ ("${id}"),
    params: /** @type {${typeName}[]} */ ([${params.map((p) => `"${p}"`).join(", ")}]),
  }`;
    })
    .join(",\n");

  const output = `// Generated by generate_extension_config.ts — do not edit manually.

${typedefs.join("\n")}

export const forms = {
${formEntries},
};

export const views = {
${viewEntries},
};
`;

  const outPath = `${import.meta.dirname}/browser/ext_static/extension_config.js`;
  fs.writeFileSync(outPath, output);
  console.log(`Generated ${outPath}`);
})();
