import fs from "node:fs";
import * as default_config from "./default_config.ts";

// Form/view IDs used by the browser extension.
// If a name here doesn't match the config, this script will fail at the
// buildGlobal() call or at the assertion below.
const EXTENSION_FORM_IDS = [
  "capture-microblog",
  "capture-profile",
  "capture-image",
] as const;

const EXTENSION_VIEW_IDS = [
  "microblog-exists",
  "profile-exists",
  "image-exists",
] as const;

function toPascalCase(s: string): string {
  return s
    .split(/[-_]/)
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join("");
}

(async () => {
  const config = await default_config.buildGlobal();

  // Validate and extract form field definitions
  const forms: Record<string, { id: string; type: string }[]> = {};
  for (const formId of EXTENSION_FORM_IDS) {
    const form = config.forms[formId];
    if (!form) {
      throw new Error(
        `Browser extension form "${formId}" not found in config`,
      );
    }
    forms[formId] = form.fields
      .filter((f) => f.type !== "id" && f.type !== "datetime_now")
      .map((f) => ({ id: f.id, type: "string" }));
  }

  // Validate and extract view parameter definitions
  const views: Record<string, { id: string; type: string }[]> = {};
  for (const viewId of EXTENSION_VIEW_IDS) {
    const view = config.views[viewId];
    if (!view) {
      throw new Error(
        `Browser extension view "${viewId}" not found in config`,
      );
    }
    views[viewId] = Object.keys(view.parameters ?? {}).map((k) => ({
      id: k,
      type: "string",
    }));
  }

  // Generate JSDoc @typedef for each form's params as an object type
  const typedefs: string[] = [];
  for (const [id, fields] of Object.entries(forms)) {
    const name = toPascalCase(id) + "Params";
    const props = fields
      .map((f) => ` * @property {${f.type}} [${f.id}]`)
      .join("\n");
    typedefs.push(`/**\n * @typedef {Object} ${name}\n${props}\n */`);
  }
  for (const [id, fields] of Object.entries(views)) {
    const name = toPascalCase(id) + "Params";
    const props = fields
      .map((f) => ` * @property {${f.type}} [${f.id}]`)
      .join("\n");
    typedefs.push(`/**\n * @typedef {Object} ${name}\n${props}\n */`);
  }

  // Generate form entries with literal id types
  const formEntries = Object.entries(forms)
    .map(([id]) => {
      return `  "${id}": /** @type {"${id}"} */ ("${id}")`;
    })
    .join(",\n");

  // Generate view entries with literal id types
  const viewEntries = Object.entries(views)
    .map(([id]) => {
      return `  "${id}": /** @type {"${id}"} */ ("${id}")`;
    })
    .join(",\n");

  const output = `// Generated by generate_extension_config.ts — do not edit manually.

${typedefs.join("\n\n")}

export const forms = {
${formEntries},
};

export const views = {
${viewEntries},
};
`;

  const outPath = `${import.meta.dirname}/browser/ext_static/extension_config.js`;
  fs.writeFileSync(outPath, output);
  console.log(`Generated ${outPath}`);
})();
