on:
  push:
    branches:
      - master
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: false
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          set -xeu
          export PAGES_DIR=$(pwd)/stage/pages/static
          export STATIC_DIR=$(pwd)/stage/static
          mkdir -p $STATIC_DIR
          (cd source/native; cargo run --bin generate_jsonschema -- $PAGES_DIR/jsonschema)
      - uses: actions/configure-pages@v5
      - uses: actions/upload-pages-artifact@v3
        with:
          path: ./stage/pages/static
      - uses: actions/deploy-pages@v4
